/**
 * Handle suggestion vocabulary — English.
 *
 * DATA, not copy. `suggestHandle` (`handle.ts`) draws one adjective and one
 * animal from these lists and appends two digits, giving a readable account
 * name like `quick-otter-42` instead of the Crockford string `generateHandle`
 * mints. Nothing else reads them.
 *
 * ── The bar these words have to clear ────────────────────────────────────
 *
 * A CHILD HAS TO RECOGNISE THE ANIMAL AND SMILE (owner decision,
 * 2026-09-02). That is the whole selection rule, and it is stricter than
 * "valid word": `quick-guillemot-42` passes every mechanical check in
 * `sync-handle-words.test.ts` and still fails, because nobody knows what a
 * guillemot is. So: everyday animals only, no obscure birds, no antelope or
 * fish species, and no insects beyond the bee, the butterfly and the
 * ladybird. Adjectives are the plain warm ones a person would actually say,
 * with only a handful of basic colours.
 *
 * The test pins fifteen anchor animals for exactly this reason. A list that
 * has drifted back towards obscure fauna will have lost them first.
 *
 * ── Provenance ───────────────────────────────────────────────────────────
 *
 * Written by hand for this repo (owner decision, 2026-09-02).
 * Every entry then passed one mechanical filter: lowercase, `^[a-z]+$` (so no
 * umlaut, no sz-ligature, no hyphen, no space), 3 to 10 (9 for an animal) letters,
 * deduped, sorted — plus a short hand-curated removal list for words a filter
 * cannot judge.
 *
 * ── Why the shape rules ──────────────────────────────────────────────────
 *
 * ASCII only because this string is dictated down a phone and typed on a
 * second device's keyboard, which may have no umlaut key. Length-bounded
 * because the whole handle must stay inside the service's 64-character limit
 * and stay transcribable. Positive or neutral only, and nothing that reads as
 * insulting, political, medical or sexual once an adjective and an animal sit
 * next to each other — the pair is what a person is shown, not the words.
 */

/** 152 English adjectives, in the uninflected base form. */
export const EN_HANDLE_ADJECTIVES: readonly string[] = [
  'agile',
  'alert',
  'amber',
  'bold',
  'bouncy',
  'brave',
  'bright',
  'brisk',
  'bubbly',
  'busy',
  'calm',
  'careful',
  'caring',
  'cheerful',
  'cheery',
  'chirpy',
  'clean',
  'clear',
  'clever',
  'comfy',
  'cool',
  'cosy',
  'crafty',
  'crisp',
  'cuddly',
  'curious',
  'cute',
  'daring',
  'dreamy',
  'eager',
  'early',
  'easy',
  'fair',
  'fancy',
  'fast',
  'fine',
  'fluffy',
  'fond',
  'free',
  'fresh',
  'friendly',
  'frosty',
  'funny',
  'fuzzy',
  'gentle',
  'giggly',
  'glad',
  'golden',
  'good',
  'grand',
  'grassy',
  'great',
  'green',
  'handy',
  'happy',
  'hardy',
  'helpful',
  'honest',
  'hopeful',
  'hungry',
  'jolly',
  'joyful',
  'keen',
  'kind',
  'kindly',
  'laughing',
  'lazy',
  'leafy',
  'light',
  'lively',
  'loud',
  'lovely',
  'loyal',
  'lucky',
  'merry',
  'mighty',
  'mild',
  'minty',
  'misty',
  'neat',
  'nice',
  'nimble',
  'noble',
  'open',
  'patient',
  'peppy',
  'perky',
  'playful',
  'pleasant',
  'plucky',
  'polite',
  'pretty',
  'proud',
  'quick',
  'quiet',
  'rapid',
  'ready',
  'red',
  'rosy',
  'round',
  'sandy',
  'shiny',
  'short',
  'shy',
  'silent',
  'silky',
  'silly',
  'silver',
  'simple',
  'sleek',
  'sleepy',
  'slow',
  'small',
  'smart',
  'smiling',
  'smooth',
  'snappy',
  'snowy',
  'soft',
  'sparkly',
  'speedy',
  'spry',
  'starry',
  'steady',
  'strong',
  'sturdy',
  'sunny',
  'super',
  'sweet',
  'swift',
  'tall',
  'tame',
  'tender',
  'tidy',
  'timid',
  'tiny',
  'true',
  'trusty',
  'warm',
  'watchful',
  'wavy',
  'wide',
  'wild',
  'willing',
  'windy',
  'winter',
  'wise',
  'witty',
  'wobbly',
  'woolly',
  'young',
  'zippy',
];

/** 128 English animal names a child would recognise. */
export const EN_HANDLE_ANIMALS: readonly string[] = [
  'alligator',
  'alpaca',
  'anteater',
  'armadillo',
  'badger',
  'bear',
  'bee',
  'bison',
  'blackbird',
  'bluebird',
  'budgie',
  'buffalo',
  'bunny',
  'butterfly',
  'calf',
  'camel',
  'canary',
  'cat',
  'cheetah',
  'chipmunk',
  'cow',
  'coyote',
  'crab',
  'crane',
  'crocodile',
  'cub',
  'deer',
  'dingo',
  'dog',
  'dolphin',
  'dormouse',
  'duck',
  'duckling',
  'eagle',
  'elephant',
  'elk',
  'emu',
  'falcon',
  'fawn',
  'ferret',
  'finch',
  'flamingo',
  'foal',
  'fox',
  'frog',
  'gecko',
  'gerbil',
  'giraffe',
  'goat',
  'goldfish',
  'goose',
  'gosling',
  'hamster',
  'hare',
  'hedgehog',
  'hen',
  'heron',
  'hippo',
  'horse',
  'iguana',
  'jaguar',
  'kangaroo',
  'kitten',
  'kiwi',
  'koala',
  'lamb',
  'lark',
  'lemur',
  'leopard',
  'lion',
  'lizard',
  'llama',
  'lobster',
  'macaw',
  'magpie',
  'manatee',
  'meerkat',
  'mole',
  'moose',
  'mouse',
  'narwhal',
  'newt',
  'octopus',
  'okapi',
  'ostrich',
  'otter',
  'owl',
  'panda',
  'panther',
  'parrot',
  'pelican',
  'penguin',
  'pony',
  'possum',
  'puffin',
  'puma',
  'puppy',
  'rabbit',
  'raccoon',
  'raven',
  'reindeer',
  'rhino',
  'robin',
  'rooster',
  'salmon',
  'seagull',
  'seahorse',
  'seal',
  'shark',
  'sheep',
  'sloth',
  'sparrow',
  'squid',
  'squirrel',
  'starfish',
  'stork',
  'swan',
  'tapir',
  'tiger',
  'toucan',
  'turtle',
  'walrus',
  'whale',
  'wolf',
  'wombat',
  'wren',
  'yak',
  'zebra',
];
