/**
 * Handle suggestion vocabulary — German.
 *
 * DATA, not copy. `suggestHandle` (`handle.ts`) draws one adjective and one
 * animal from these lists and appends two digits, giving a readable account
 * name like `flink-otter-42` instead of the Crockford string `generateHandle`
 * mints. Nothing else reads them.
 *
 * ── The bar these words have to clear ────────────────────────────────────
 *
 * A CHILD HAS TO RECOGNISE THE ANIMAL AND SMILE (owner decision,
 * 2026-09-02). That is the whole selection rule, and it is stricter than
 * "valid word": `quick-guillemot-42` passes every mechanical check in
 * `sync-handle-words.test.ts` and still fails, because nobody knows what a
 * guillemot is. So: everyday animals only, no obscure birds, no antelope or
 * fish species, and no insects beyond the bee, the butterfly and the
 * ladybird. Adjectives are the plain warm ones a person would actually say,
 * with only a handful of basic colours.
 *
 * The test pins fifteen anchor animals for exactly this reason. A list that
 * has drifted back towards obscure fauna will have lost them first.
 *
 * ── Provenance ───────────────────────────────────────────────────────────
 *
 * Produced by `djinn`'s wordsmith CLI (`pnpm -C djinn wordsmith translate`,
 * google/gemini-3.7-flash) from the English lists in `handle-words.en.ts`, with
 * notes asking for the everyday German name a child uses, one word, lowercase,
 * and no umlaut or sz-ligature — SKIPPING a word rather than misspelling it,
 * which is why the German lists are shorter (`baer`, `loewe` and `kaenguru`
 * are not German, so the bear, the lion and the kangaroo simply do not appear).
 * Every entry then passed one mechanical filter: lowercase, `^[a-z]+$` (so no
 * umlaut, no sz-ligature, no hyphen, no space), 3 to 10 (9 for an animal) letters,
 * deduped, sorted — plus a short hand-curated removal list for words a filter
 * cannot judge.
 *
 * ── Why the shape rules ──────────────────────────────────────────────────
 *
 * ASCII only because this string is dictated down a phone and typed on a
 * second device's keyboard, which may have no umlaut key. Length-bounded
 * because the whole handle must stay inside the service's 64-character limit
 * and stay transcribable. Positive or neutral only, and nothing that reads as
 * insulting, political, medical or sexual once an adjective and an animal sit
 * next to each other — the pair is what a person is shown, not the words.
 */

/** 109 German adjectives, in the uninflected base form. */
export const DE_HANDLE_ADJECTIVES: readonly string[] = [
  'achtsam',
  'albern',
  'angenehm',
  'belaubt',
  'bequem',
  'bereit',
  'cool',
  'edel',
  'ehrlich',
  'eifrig',
  'einfach',
  'emsig',
  'fair',
  'fein',
  'fidel',
  'flauschig',
  'flink',
  'frei',
  'freudig',
  'freundlich',
  'frisch',
  'froh',
  'frostig',
  'funkelnd',
  'geduldig',
  'glatt',
  'golden',
  'grasig',
  'gut',
  'handlich',
  'heiter',
  'hell',
  'herzlich',
  'hilfreich',
  'hungrig',
  'jung',
  'keck',
  'kichernd',
  'klar',
  'klein',
  'klug',
  'knackig',
  'knuddelig',
  'kurz',
  'kuschelig',
  'lachend',
  'langsam',
  'laut',
  'leicht',
  'leise',
  'lieb',
  'lieblich',
  'lustig',
  'mild',
  'minzig',
  'munter',
  'mutig',
  'neblig',
  'nett',
  'neugierig',
  'niedlich',
  'offen',
  'pfiffig',
  'prima',
  'quirlig',
  'rasch',
  'robust',
  'rosig',
  'rot',
  'ruhig',
  'rund',
  'sandig',
  'sanft',
  'sauber',
  'scheu',
  'schick',
  'schlau',
  'schnell',
  'seidig',
  'silbern',
  'sonnig',
  'stark',
  'stetig',
  'still',
  'stolz',
  'super',
  'tapfer',
  'toll',
  'treu',
  'verschneit',
  'verspielt',
  'wach',
  'wachsam',
  'wackelig',
  'wahr',
  'warm',
  'weich',
  'weise',
  'weit',
  'wellig',
  'wild',
  'willig',
  'windig',
  'winzig',
  'witzig',
  'wollig',
  'zackig',
  'zahm',
  'zart',
];

/** 100 German animal names a child would recognise. */
export const DE_HANDLE_ANIMALS: readonly string[] = [
  'adler',
  'alligator',
  'alpaka',
  'amsel',
  'ara',
  'biene',
  'bison',
  'dachs',
  'delfin',
  'dingo',
  'eidechse',
  'elch',
  'elefant',
  'elster',
  'emu',
  'entchen',
  'ente',
  'eule',
  'falke',
  'faultier',
  'fink',
  'flamingo',
  'fohlen',
  'frettchen',
  'frosch',
  'fuchs',
  'gans',
  'gecko',
  'gepard',
  'giraffe',
  'goldfisch',
  'hahn',
  'hai',
  'hamster',
  'hase',
  'henne',
  'hummer',
  'hund',
  'igel',
  'jaguar',
  'kalb',
  'kalmar',
  'kamel',
  'katze',
  'kiwi',
  'koala',
  'kojote',
  'krabbe',
  'krake',
  'kranich',
  'krokodil',
  'kuh',
  'lachs',
  'lama',
  'lamm',
  'leguan',
  'lemur',
  'leopard',
  'lerche',
  'maulwurf',
  'maus',
  'molch',
  'narwal',
  'nashorn',
  'nilpferd',
  'okapi',
  'opossum',
  'otter',
  'panda',
  'panther',
  'papagei',
  'pelikan',
  'pferd',
  'pinguin',
  'pony',
  'puma',
  'rabe',
  'reh',
  'rehkitz',
  'reiher',
  'rennmaus',
  'rentier',
  'robbe',
  'schaf',
  'schwan',
  'seekuh',
  'seestern',
  'spatz',
  'storch',
  'tapir',
  'tiger',
  'tukan',
  'wal',
  'walross',
  'welpe',
  'wolf',
  'wombat',
  'yak',
  'zebra',
  'ziege',
];
